version: '2.1'
services:
  emerald:
    extends:
      file: config.yml
      service: emerald
    image: myriade/emerald:dev
    command: ["bash", "-c", "npm install && npm run start:dev"]
    volumes:
      - ${EMERALD_DIR}:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8088:8088"
      - "9878:9878"
      - "12345:12345"
      - "12346:12346"
      - "12347:12347"
  diamond:
    extends:
      file: config.yml
      service: diamond
    image: myriade/diamond:dev
    command: ["bash", "-c", "npm install && npm run migration:up && npm run start:dev"]
    volumes:
      - ${DIAMOND_DIR}:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8180:8180"
      - "9873:9873"
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
  cache:
    image: redis:3.2.3
    ports:
        - "6379:6379"
    healthcheck:
        test: "redis-cli -h localhost ping | grep -q 'PONG'"
        interval: 1s
        timeout: 1s
        retries: 60
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=myriade
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgres/data
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 1s
      timeout: 1s
      retries: 100
volumes:
  db_data: