version: '2.1'
services:
  sapphire:
    environment:
      service__shared_secret: a3853658-dc44-444a-84d1-dda85487d53c
      rabbitmq__url: amqp://guest:guest@mq:5672/
      rabbitmq__queue: Miner::Metrics
      rabbitmq__debug: 0
      db__host: db
      db__port: 5432
      monero__daemon__host: daemon.myriade.io
      monero__daemon__port: 80
      godKey: jenkins
      godMode: 1
      diamond__public_key: |-
          -----BEGIN PUBLIC KEY-----
          MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCMDGmqdndEOC3sn8+WYfFIkHoZ
          6vSyAtg16ETidiNJ9wGKXciAZlIovGzZ7Ebshs3qdtqODWFZvr38LTo7Z7h12Ghx
          NhkFn5ZwTd/Z6vLiYkEXaMN+/cDcaKzqCg7cwA//raBWhQmYjueQAfUazB6rQoSm
          aRKeRBWGGv5wfi3MfwIDAQAB
          -----END PUBLIC KEY-----
  diamond:
    environment:
      NODE_ENV: local
      service__shared_secret: a3853658-dc44-444a-84d1-dda85487d53c
      db__host: db
      db__port: 5432
      mail__sendgrid_key: a3853658-dc44-444a-84d1-dda85487d53c
      jwt__public_key: |-
          -----BEGIN PUBLIC KEY-----
          MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA3cjQj3fbMQ/wEDuewXtg
          45XgLW7l5PMMHa5Yxm7Urnseer1xvCf2cmJgjeP++NctQmjYXuk5wwOSjk7qT7B1
          MpswfInvDV25EvCIsCP8Zzvbu9cHLjK0vNRX4B1gj2AxpdmUpU2ZksT+1h22CxPZ
          G/Pn7lugpb5fqAog2xazMxgbqGm2qMJEjMGJkWSO0xpLjfkcFvrU5CNCkKpEMsOI
          M/umuK2UcRqOxZz+JUN3cfLWvqswxbvbfnZZ9qmfGgpr0gnsYUrWWNjqDGXIlIpy
          FMsspzaoAR797WnyowMJEZdT+7WI2+TB0rZ4HtXJpwx3G41+PDQF2YTtKfEFd1WM
          /xmGZdYyS066sHz7fJAZXe0tWDJj/4sD6s2UJZkb+jcYTiKzwYop+nENaww/SkOE
          NJNcF4jgesriYKF39ok14hGVRji2FBtbKe8YNSAP6Q7dE1Hpwju+/FvFV2P4MR8K
          zfdeSN1vO/ADqw2ALnDVsFNJJu8jy6BxVsu2W8Zd3j0orsWnjwkJZfBmkJvKGPOf
          u+YV6ZS9xAOlQuF9CY82h3b6vjrsSPnYuVtqKEj4UW5jRHT0Jd7UeIdrmm9CgwKZ
          Q9YDEEYnwJBDdpRjUTSd9zIAucEj9E0qNmxPew9TfkvTSRE/I0621mtcYGDF2Dmf
          jgrpKMIaO8RCitqcdlxcPuUCAwEAAQ==
          -----END PUBLIC KEY-----
      jwt__private_key: |-
          -----BEGIN RSA PRIVATE KEY-----
          MIIJKQIBAAKCAgEA3cjQj3fbMQ/wEDuewXtg45XgLW7l5PMMHa5Yxm7Urnseer1x
          vCf2cmJgjeP++NctQmjYXuk5wwOSjk7qT7B1MpswfInvDV25EvCIsCP8Zzvbu9cH
          LjK0vNRX4B1gj2AxpdmUpU2ZksT+1h22CxPZG/Pn7lugpb5fqAog2xazMxgbqGm2
          qMJEjMGJkWSO0xpLjfkcFvrU5CNCkKpEMsOIM/umuK2UcRqOxZz+JUN3cfLWvqsw
          xbvbfnZZ9qmfGgpr0gnsYUrWWNjqDGXIlIpyFMsspzaoAR797WnyowMJEZdT+7WI
          2+TB0rZ4HtXJpwx3G41+PDQF2YTtKfEFd1WM/xmGZdYyS066sHz7fJAZXe0tWDJj
          /4sD6s2UJZkb+jcYTiKzwYop+nENaww/SkOENJNcF4jgesriYKF39ok14hGVRji2
          FBtbKe8YNSAP6Q7dE1Hpwju+/FvFV2P4MR8KzfdeSN1vO/ADqw2ALnDVsFNJJu8j
          y6BxVsu2W8Zd3j0orsWnjwkJZfBmkJvKGPOfu+YV6ZS9xAOlQuF9CY82h3b6vjrs
          SPnYuVtqKEj4UW5jRHT0Jd7UeIdrmm9CgwKZQ9YDEEYnwJBDdpRjUTSd9zIAucEj
          9E0qNmxPew9TfkvTSRE/I0621mtcYGDF2DmfjgrpKMIaO8RCitqcdlxcPuUCAwEA
          AQKCAgEAnCEacWU28Tr/DO5rvFlWw+BmiJVhUeOny91IsaikIJCbzFxBDOw1GiEX
          R8wRWqxgODgG2gnll9uT+IqleKQIXS/S2llf6FDqUOLz1sv+i84fygR+EY+wnJ3/
          ns4Pg998E/0wH46ZZjE4FROla/b1CDCUPcBTP1rdjDZVGubIEFgQYGbLJ9Ja35v/
          dFMOGJ6SQcf0dljuNgx8d8rlZ7cu0yl9HNVVgqnniEYUw7bTB2yksGVjWE//HO/E
          NVkDoBll/d7ugS9l5fYODdw5cBhmZy0AqlZXvzJKIDBNl2QzpiaaAMCzL9nCeMvr
          lAl8hBTKZKMfEtKsq4xgSP5bkr6vGja3GJhKqEC7So0rK3AbYxLJ+3TAKa8+QJGh
          CKGZIzletaNv9DXuHw92xFuEl/7m1IkKCOKQPzgLBjDXsIFQRInDup7ku/GSr6y0
          HfdhtByK3fxf++Kani/q6dn5UTK7MpwpGj6Psv5uUsJBVS+z7MsmQGIbeZRZhPSj
          Et2GOwApCF/Cdm+GOlfTDVfDb3FoyQ3yBt7BXPyG1lmPgysigpVOtB2jqyJOszBv
          ukVLQUxOClP7NevvJhLsbK8M1f5dtlxSDdCMf+pT/3u8YLWycXh0cMcbSgJc8hxQ
          ACHP9ssp9foZFfniBBZLCA9FF3ofNZj+1Ot19k01JKClGN9oxKECggEBAPriTeyh
          4Rq23gmkeXQatxd8UAN7CJZpWlZcDFXp3Mj/VKdAmqu6eIo6yN5B7IW5x9Y+/moy
          qKHXEvbC+niZKWeTtm+IXN42ByGWz1KrK31nLZ6qD5d2/hdMV0b974/tGFAQ+Eap
          l7txaYQLMpUtedwKUkn96KxVc1jO1CNKt+j2mdxctsiOMgUcG6YezkYvyaCV3ZgZ
          L3oHlsoHVOuo5pjyPmGVVNT91dDpWZuZmneBizsTMk0RMybpdCTuA0pHUzDuNzlu
          ooIzd/cXoAU1s3SoyRX/o0LkswKG8UJhchuhqPVHnC4+Ld6wEriNPSixpXX1BWNQ
          +nvJ3F/OLJBluZsCggEBAOJOmeQhZCWzlxkP8IkzrkIQqKlzvPC9/S2+dMf1OpSp
          g/f6gBsEAqXCJLgsC6TZivgpNL/mJIDKrj01Fo9516MrIZgWFZP7AKAeCXNfFWHh
          LNFmtzMYALHjndmTQKYWABmWQdppkSC4sQrr3Vsj8tHfugJCAnjGYpftCXnUd6lF
          E+4o2gQ3rKwMgOKTriySBkxz0A4tBA7mPBea1Y/bUw1B7s0WzhzPZ9RaTkWkozaK
          l7M2K68ISX5p6h837YY6HtgVdRy8ON+QXKKOhQFP/NT4icBtPnQasjGeHuXv0yEN
          cNrwpZtMxHgrZwkkMWvN0NTwr/E248d0GWJhqANDsX8CggEAMmerPkKbxlE9NPS9
          jg0cAfTw4nIinI2YH8eols5AlIVwDZZWPPBe7W64EqduDMPxmWLYnJ+G79UVM0yj
          I/2pquyrd6cO+XojXqU9DB/lwfEr4jfKoCTBEg89bb7xFZqOCvAN4ayLFpbHm0bg
          p8YWOJY+SC1iRNV6MjqDtn95ia2Z5gMemhaviAVIrMx9pu5M9R2HAtr0hfDmY7qr
          Xhl2Ev6Ad/yXqZ9CCRII9dEbjq0ROxI1RfSRsVywAAdt08uWtDr4D2rh7YTHsnYl
          qUZLwsFyfR/6PiNSr8xKxoprcY++MWFsyIGnl5kKedeulPF0C8nphjWrzZkV1I3I
          uE4nxwKCAQEArYMmastPRbjUeNrHyepeCTlMl9+tVcfVfmUwlL9pEuKF1HO0FQKW
          JREdpjffFZ3V9z9gumFyS20a+sLhcVAyDWDceQc1tCgW6q0dAeA9PLaw7jya6gnV
          Po8OT+ue/biQiw2xoAygwT3aQE1ngqGlY1TuAR0rV/6DSYjsYwSMWrQj+85GmkU1
          lxRfHVmtiW7MdYG2W6gYHHRaTp7gb1Px8ZBDz+tUTLKZIS+8I5l/qinI9hbql2D7
          OHlskFMJQoj9bR/GkymdUYwV+mzbfY4ehAurUmZwJATz6ycY+aNPdWAgzz0DPHc3
          jAt7DH87hTRgkWOZApDbQ+m4LL5DW31jcQKCAQAlWsuMZrIX4cFeTzd/HL6cfTkU
          LRN+tRcyLRZ3KmF6xw6IkXaZvQzSMBptuqpmSJZBl7PU3215lrCjTCe6FB4t9u7H
          NBeTFgbcC6dIQVWzzf+k9qSDdzBNlgDua5Oz0hEb/5HfS2xslyP99SQYheEnnpm1
          TZ6P5m0jI0imrEplI/KJltENEBcfelh0Iz80sziultjm7kWKEQkSsWoWDrcQ5gZf
          BjXM0QAtMwyxqg148fI7Ne6Few28txBXpmFGrVAaHAQHdpcUG/ykBdYfF4hY5mCX
          MMSpikRa+zd+6j8ch/zTXNtvLO6r08MORa9kHR3ZFKjx0kgbIp1Qmkp+t39L
          -----END RSA PRIVATE KEY-----